spring:
  datasource:
    url: jdbc:mysql://192.168.1.91:3306/dawn?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: homeMysql91
    type: com.alibaba.druid.pool.DruidDataSource

