management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  oauth2:
    client:
      client-id: dawn-admin
      client-secret: dawn-admin
      user-authorization-uri: http://127.0.0.1:8080/dawn-auth/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/dawn-auth/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/dawn-auth/oauth/token_key
